logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: _a_b_c_d_a_p_p_
    root_packages: com.apps.abcd
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false